version 1.1-1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1251,8 +1251,6 @@ fi
 CC=`${R_HOME}/bin/R CMD config CC`
 CFLAGS=`${R_HOME}/bin/R CMD config CFLAGS`
 FLIBS=`${R_HOME}/bin/R CMD config FLIBS`
-LIBS=`grep "^LIBS" ${R_HOME}/etc/Makeconf | sed "s/^LIBS *= *//"`
-LIBS0=${LIBS}
 BLAS_LIBS=`${R_HOME}/bin/R CMD config BLAS_LIBS`
 LAPACK_LIBS=`${R_HOME}/bin/R CMD config LAPACK_LIBS`
 
@@ -1266,17 +1264,19 @@ if ${have_f77_underscore}; then
   scopy_func=scopy_
   lsame_func=lsame_
   sgesdd_func=sgesdd_
+  xerbla=xerbla_
 else
   scopy_func=scopy
   lsame_func=lsame
   sgesdd_func=sgesdd
+  xerbla=xerbla
 fi
 
 if test -z "${BLAS_LIBS}"; then
-  echo "it seems you are not using a BLAS library: using our BLAS routines"
+  echo "it seems you are not using a BLAS library: using our BLAS and LAPACK routines"
   (cd src; ln -s sblas.unused sblas.f; ln -s lsame.unused lsame.f; ln -s slapack.unused slapack.f)
 else
-  LIBS="${BLAS_LIBS} ${FLIBS} ${LIBS}"
+  LIBS="${BLAS_LIBS} ${FLIBS}"
   ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -2208,59 +2208,17 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
-as_ac_var=`echo "ac_cv_func_${scopy_func}" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for ${scopy_func}" >&5
-echo $ECHO_N "checking for ${scopy_func}... $ECHO_C" >&6
-if eval "test \"\${$as_ac_var+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
+cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-/* Define ${scopy_func} to an innocuous variant, in case <limits.h> declares ${scopy_func}.
-   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
-#define ${scopy_func} innocuous_${scopy_func}
-
-/* System header to define __stub macros and hopefully few prototypes,
-    which can conflict with char ${scopy_func} (); below.
-    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
-    <limits.h> exists even on freestanding compilers.  */
-
-#ifdef __STDC__
-# include <limits.h>
-#else
-# include <assert.h>
-#endif
-
-#undef ${scopy_func}
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-{
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char ${scopy_func} ();
-/* The GNU C library defines this for functions which it implements
-    to always fail with ENOSYS.  Some functions are actually named
-    something starting with __ and the normal name is an alias.  */
-#if defined (__stub_${scopy_func}) || defined (__stub___${scopy_func})
-choke me
-#else
-char (*f) () = ${scopy_func};
-#endif
-#ifdef __cplusplus
-}
-#endif
-
+void ${xerbla}(char *srname, int *info){}
 int
 main ()
 {
-return f != ${scopy_func};
+${scopy_func}()
   ;
   return 0;
 }
@@ -2287,29 +2245,25 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  eval "$as_ac_var=yes"
+  blas_ok=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-eval "$as_ac_var=no"
+blas_ok=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
-if test `eval echo '${'$as_ac_var'}'` = yes; then
-  :
-else
-  NO_SBLAS=1
-fi
-
-  if test ${NO_SBLAS}; then
-    echo "could not find SCOPY in your BLAS library, using our BLAS routines"
+  echo "$as_me:$LINENO: checking for scopy in ${BLAS_LIBS}" >&5
+echo $ECHO_N "checking for scopy in ${BLAS_LIBS}... $ECHO_C" >&6
+  echo "$as_me:$LINENO: result: ${blas_ok}" >&5
+echo "${ECHO_T}${blas_ok}" >&6
+  if test "${blas_ok}" = no; then
+    { echo "$as_me:$LINENO: WARNING: could not find scopy in your BLAS library, using our BLAS and LAPACK routines" >&5
+echo "$as_me: WARNING: could not find scopy in your BLAS library, using our BLAS and LAPACK routines" >&2;}
     (cd src; ln -s sblas.unused sblas.f; ln -s lsame.unused lsame.f; ln -s slapack.unused slapack.f)
   else
-    LIBS="${LAPACK_LIBS} ${BLAS_LIBS} ${FLIBS} ${LIBS0}"
+    LIBS="${LAPACK_LIBS} ${BLAS_LIBS} ${FLIBS}"
     as_ac_var=`echo "ac_cv_func_${sgesdd_func}" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for ${sgesdd_func}" >&5
 echo $ECHO_N "checking for ${sgesdd_func}... $ECHO_C" >&6
@@ -2408,7 +2362,8 @@ else
 fi
 
     if test ${NO_LIBLAPACK}; then
-      echo "could not find SGESDD: using our LAPACK routines"
+      { echo "$as_me:$LINENO: WARNING: could not find sgesdd: using our LAPACK routines" >&5
+echo "$as_me: WARNING: could not find sgesdd: using our LAPACK routines" >&2;}
       (cd src; ln -s slapack.unused slapack.f)
     fi
     as_ac_var=`echo "ac_cv_func_${lsame_func}" | $as_tr_sh`
@@ -2509,7 +2464,8 @@ else
 fi
 
     if test ${NO_LSAME}; then
-      echo "could not find LSAME in your BLAS or LAPACK library, using our copy"
+      { echo "$as_me:$LINENO: WARNING: could not find LSAME in your BLAS or LAPACK library, using our copy" >&5
+echo "$as_me: WARNING: could not find LSAME in your BLAS or LAPACK library, using our copy" >&2;}
       (cd src; ln -s lsame.unused lsame.f)
     fi
   fi
